spring:
  application:
    name: mos-seller-mcrs
  datasource:
    url: jdbc:mysql://mysql-32514b67-lambro2510-7aba.h.aivencloud.com:16150/defaultdb?useSSL=true&requireSSL=true
    username: avnadmin
    password: AVNS_lfFBT9tnsX0JpFgIf1H
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 3000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.openfeign: DEBUG